### ISSUE TITLE
Implement: story outline

### ISSUE THREAD

**Issue by nagisc007** [nagisc007/prj_kakuyomu#27]
勇謎３：全体概要の作成
===

**Description**
まずは全体の概要作成。

**Expected behavior**
nothing
**Current behavior**
nothing
**Tasks**
- [ ] prepare story file
- [ ] prepare story test
- [ ] implement story outline test
- [ ] pass outline test

**Note**
nothing
